version: 2

project_name: xcli

builds:
  - id: xcli
    main: .
    binary: xcli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/Garden12138/xcli/cmd.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto
  make_latest: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
